tekup_seance2:
    resource: "@TekupSeance2Bundle/Resources/config/routing.yml"
    prefix:   /

tekup_first:
    resource: "@TekupFirstBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
